# Generated by Django 2.1.5 on 2019-01-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190106_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='bgColor',
            new_name='bg_color',
        ),
    ]
