FROM        python:3.6.7-slim
MAINTAINER  smallbee3@gmail.com

ENV         LANG    C.UTF-8

# Backend
RUN         apt-get -y update
RUN         apt-get -y dist-upgrade
RUN         apt-get -y install build-essential nginx supervisor

COPY        requirements.txt /tmp/requirements.txt
RUN         pip3 install -r /tmp/requirements.txt

# Frontend
RUN     apt-get -y install git curl
RUN     curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN     apt-get -y install nodejs