# Generated by Django 2.1.5 on 2019-01-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0003_auto_20190106_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Card's title")),
                ('description', models.TextField(verbose_name="Card's description")),
                ('pos', models.PositiveIntegerField(default=65535, verbose_name="Card's position data")),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('listId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.List')),
            ],
        ),
    ]
