# Generated by Django 2.1.5 on 2019-01-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20190110_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to='card', verbose_name="Card's attached image"),
        ),
    ]
