# Generated by Django 2.1.5 on 2019-01-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20190113_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='img_cover',
            new_name='image',
        ),
    ]
