# Generated by Django 2.1.5 on 2019-01-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_auto_20190106_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="List's title")),
                ('pos', models.PositiveIntegerField(blank=True, max_length=1000, verbose_name="List's position data")),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('boardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
            ],
        ),
    ]
