# Generated by Django 2.1.5 on 2019-01-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20190106_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='pos',
            field=models.PositiveIntegerField(default=65535, verbose_name="List's position data"),
        ),
    ]
