# Generated by Django 2.1.5 on 2019-01-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190106_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='pos',
            field=models.DecimalField(decimal_places=7, default=65535, max_digits=15, verbose_name="List's position data"),
        ),
    ]
