# Generated by Django 2.1.5 on 2019-01-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20190109_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='boardId',
            new_name='board_id',
        ),
    ]
